# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalkulator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(200, 310)
        window.setFixedSize(200, 310)
        window.setStyleSheet("QLabel, QPushButton { \n"
"border: 1px solid red;\n"
"background-color:rgb(24,24,24); \n"
"color:white;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background: rgb(79,79,79);\n"
"}\n"
"\n"
"QTextEdit {\n"
"background-color:rgb(24,24,24); \n"
"border: 1px solid red;\n"
"}\n"
"\n"
"")
        window.setWindowIcon(QtGui.QIcon("calculator_icon.png")) 
        self.num1 = QtWidgets.QPushButton(window)
        self.num1.setGeometry(QtCore.QRect(0, 210, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num1.setFont(font)
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QPushButton(window)
        self.num2.setGeometry(QtCore.QRect(50, 210, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num2.setFont(font)
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QPushButton(window)
        self.num3.setGeometry(QtCore.QRect(100, 210, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.num3.setFont(font)
        self.num3.setObjectName("num3")
        self.num4 = QtWidgets.QPushButton(window)
        self.num4.setGeometry(QtCore.QRect(0, 160, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num4.setFont(font)
        self.num4.setObjectName("num4")
        self.num5 = QtWidgets.QPushButton(window)
        self.num5.setGeometry(QtCore.QRect(50, 160, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num5.setFont(font)
        self.num5.setObjectName("num5")
        self.num6 = QtWidgets.QPushButton(window)
        self.num6.setGeometry(QtCore.QRect(100, 160, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num6.setFont(font)
        self.num6.setObjectName("num6")
        self.num7 = QtWidgets.QPushButton(window)
        self.num7.setGeometry(QtCore.QRect(0, 110, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.num7.setFont(font)
        self.num7.setObjectName("num7")
        self.num8 = QtWidgets.QPushButton(window)
        self.num8.setGeometry(QtCore.QRect(50, 110, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num8.setFont(font)
        self.num8.setObjectName("num8")
        self.num9 = QtWidgets.QPushButton(window)
        self.num9.setGeometry(QtCore.QRect(100, 110, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num9.setFont(font)
        self.num9.setObjectName("num9")
        self.num0 = QtWidgets.QPushButton(window)
        self.num0.setGeometry(QtCore.QRect(0, 260, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num0.setFont(font)
        self.num0.setObjectName("num0")
        self.comma = QtWidgets.QPushButton(window)
        self.comma.setGeometry(QtCore.QRect(100, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comma.setFont(font)
        self.comma.setObjectName("comma")
        self.plus = QtWidgets.QPushButton(window)
        self.plus.setGeometry(QtCore.QRect(150, 210, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plus.setFont(font)
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(window)
        self.minus.setGeometry(QtCore.QRect(150, 160, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.multiply = QtWidgets.QPushButton(window)
        self.multiply.setGeometry(QtCore.QRect(150, 110, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.multiply.setFont(font)
        self.multiply.setObjectName("multiply")
        self.divide = QtWidgets.QPushButton(window)
        self.divide.setGeometry(QtCore.QRect(150, 60, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.divide.setFont(font)
        self.divide.setObjectName("divide")
        self.equally = QtWidgets.QPushButton(window)
        self.equally.setGeometry(QtCore.QRect(150, 260, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.equally.setFont(font)
        self.equally.setCheckable(False)
        self.equally.setObjectName("equally")
        self.clear_all = QtWidgets.QPushButton(window)
        self.clear_all.setGeometry(QtCore.QRect(0, 60, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_all.setFont(font)
        self.clear_all.setObjectName("clear_all")
        self.plus_minus = QtWidgets.QPushButton(window)
        self.plus_minus.setGeometry(QtCore.QRect(50, 60, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plus_minus.setFont(font)
        self.plus_minus.setObjectName("plus_minus")
        self.procent = QtWidgets.QPushButton(window)
        self.procent.setGeometry(QtCore.QRect(100, 60, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.procent.setFont(font)
        self.procent.setObjectName("procent")
        self.label = QtWidgets.QLabel(window)
        self.label.setGeometry(QtCore.QRect(0, 0, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.clear_all.raise_()
        self.num1.raise_()
        self.num2.raise_()
        self.num3.raise_()
        self.num6.raise_()
        self.plus_minus.raise_()
        self.num9.raise_()
        self.plus.raise_()
        self.num0.raise_()
        self.divide.raise_()
        self.num4.raise_()
        self.minus.raise_()
        self.comma.raise_()
        self.num5.raise_()
        self.procent.raise_()
        self.equally.raise_()
        self.num8.raise_()
        self.num7.raise_()
        self.multiply.raise_()
        self.label.raise_()

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Калькулятор"))
        self.num1.setText(_translate("window", "1"))
        self.num2.setText(_translate("window", "2"))
        self.num3.setText(_translate("window", "3"))
        self.num4.setText(_translate("window", "4"))
        self.num5.setText(_translate("window", "5"))
        self.num6.setText(_translate("window", "6"))
        self.num7.setText(_translate("window", "7"))
        self.num8.setText(_translate("window", "8"))
        self.num9.setText(_translate("window", "9"))
        self.num0.setText(_translate("window", "0"))
        self.comma.setText(_translate("window", "."))
        self.plus.setText(_translate("window", "+"))
        self.minus.setText(_translate("window", "-"))
        self.multiply.setText(_translate("window", "*"))
        self.divide.setText(_translate("window", "/"))
        self.equally.setText(_translate("window", "="))
        self.clear_all.setText(_translate("window", "c"))
        self.plus_minus.setText(_translate("window", "+/-"))
        self.procent.setText(_translate("window", "%"))
        self.label.setText(_translate("window", "0"))

